# Generated by Django 4.1 on 2022-08-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookmarks_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['-added']},
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
    ]
