# Generated by Django 4.1 on 2022-08-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_alter_bookmarks_options_alter_bookmarks_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
